# Generated by Django 4.2.19 on 2025-09-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=200, unique=True)),
                ('judul', models.CharField(max_length=255)),
                ('file_pdf', models.FileField(upload_to='surat_pdf/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arsip.kategorisurat')),
            ],
        ),
    ]
