# Generated by Django 4.2.19 on 2025-09-14 08:17

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    KategoriSurat = apps.get_model('arsip', 'KategoriSurat')
    categories = [
        'Undangan',
        'Pengumuman',
        'Nota Dinas',
        'Pemberitahuan',
    ]
    for category in categories:
        KategoriSurat.objects.create(nama_kategori=category)

def remove_initial_categories(apps, schema_editor):
    KategoriSurat = apps.get_model('arsip', 'KategoriSurat')
    KategoriSurat.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
