# Generated by Django 4.2.19 on 2025-09-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0002_create_initial_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorisurat',
            old_name='nama_kategori',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='kategorisurat',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arsip.kategorisurat'),
        ),
    ]
