# Generated by Django 4.2.19 on 2025-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0003_rename_nama_kategori_kategorisurat_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='surat_foto/'),
        ),
    ]
